In [1]:
import tarfile

tar = tarfile.open('comm-f2f-Resistance-network.tar.gz', "r:gz")
tar.extractall()
tar.close()

Code taken from the README file

In [9]:
import numpy as np
import pandas as pd

def loadGame(game, N):
	# N is the number of players in the game
	# load csv data
	# unweighted and weighted networks can be loaded exactly the same way
	# below shows the loader for weighted networks
	df_network = pd.read_csv(f'{src}/network{game}.csv', index_col = 0)

	# T is number of timestamps (10 frames)
	T = len(df_network)
	# load VFOA network to T x N x (N+1) array
	# vfoa[t, n, i] is the probability of player n+1 looking at object i at time t
	# i: 0 - laptop, 1 - player 1, 2 - player 2, ..., N - player N
	vfoa = np.reshape(df_network.values, (T,N,N+1))

	# print information
	print(f'network id:{game}\t length(x 1/3 second): {T}\t num of players: {N}')
	return vfoa

src = './network' # root dir of data
meta = pd.read_csv('network_list.csv')

Get deceiver probability information

In [15]:
node_role = pd.read_csv('node_role.csv')
node_role['node_id'] = node_role['node'].apply(lambda x: int(x[1])-1)
node_role['role'] -= 1

deceiver_prob = node_role.pivot(index='ID', columns='node_id', values='role')
deceiver_prob.head()

node_id    0    1    2    3    4    5    6    7
ID
0        0.0  0.0  1.0  0.0  1.0  0.0  1.0  NaN
2        1.0  0.0  0.0  0.0  1.0  0.0  1.0  NaN
3        1.0  0.0  0.0  0.0  0.0  1.0  1.0  NaN
4        1.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0
5        0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0

Flatten the adjacency matrix so that each row represents the gaze vector of the user.  
Convert this into the wikipedia format and save as CSV  

Note: Create an empty folder 'network_processed'.  
Then move the files into the TGN-master/data folder. (Or just use that path directly)

In [17]:
import csv

for _, meta_row in meta.iterrows():
    game = loadGame(meta_row['NETWORK'], meta_row['NUMBER_OF_PARTICIPANTS'])
    
    records = []

    t, n1, n2 = game.shape
    game = game.reshape(t*n1, n2)
    
    d_prob = [0]
    if meta_row['NETWORK'] in deceiver_prob.index:
        d_prob = deceiver_prob[deceiver_prob.index == meta_row['NETWORK']].iloc[0, :n1]
    
    for i, game_row in enumerate(game):
        # Columns are: source_userId, dest_userId, tstamp, state_label, features, deceiver_prob
        prob = d_prob[i%n1] if len(d_prob) > 1 else 0
        records.append((i%n1, np.argmax(game_row), i+1, 0, 0, prob))
    
    game_df = pd.DataFrame(records)
    game_df.to_csv(f"./network_processed/network_{meta_row['NETWORK']}.csv", index=False, header=False, quoting=csv.QUOTE_NONE, escapechar=",")

network id:0	 length(x 1/3 second): 7323	 num of players: 7
network id:1	 length(x 1/3 second): 5328	 num of players: 8
network id:2	 length(x 1/3 second): 7533	 num of players: 7
network id:3	 length(x 1/3 second): 6264	 num of players: 7
network id:4	 length(x 1/3 second): 7323	 num of players: 8
network id:5	 length(x 1/3 second): 9651	 num of players: 8
network id:6	 length(x 1/3 second): 7260	 num of players: 7
network id:7	 length(x 1/3 second): 7245	 num of players: 6
network id:8	 length(x 1/3 second): 6243	 num of players: 7
network id:9	 length(x 1/3 second): 8340	 num of players: 8
network id:10	 length(x 1/3 second): 6681	 num of players: 7
network id:11	 length(x 1/3 second): 5415	 num of players: 7
network id:12	 length(x 1/3 second): 5571	 num of players: 8
network id:13	 length(x 1/3 second): 7173	 num of players: 7
network id:14	 length(x 1/3 second): 9429	 num of players: 8
network id:15	 length(x 1/3 second): 5466	 num of players: 6
network id:16	 length(x 1/3 second): 6678	 num of players: 6
network id:17	 length(x 1/3 second): 3054	 num of players: 7
network id:18	 length(x 1/3 second): 9264	 num of players: 8
network id:19	 length(x 1/3 second): 4248	 num of players: 5
network id:20	 length(x 1/3 second): 6594	 num of players: 6
network id:21	 length(x 1/3 second): 9699	 num of players: 8
network id:22	 length(x 1/3 second): 7662	 num of players: 8
network id:23	 length(x 1/3 second): 9537	 num of players: 8
network id:24	 length(x 1/3 second): 7875	 num of players: 5
network id:25	 length(x 1/3 second): 7737	 num of players: 8
network id:26	 length(x 1/3 second): 5037	 num of players: 7
network id:27	 length(x 1/3 second): 5229	 num of players: 8
network id:28	 length(x 1/3 second): 7683	 num of players: 8
network id:29	 length(x 1/3 second): 6360	 num of players: 8
network id:30	 length(x 1/3 second): 7806	 num of players: 8
network id:31	 length(x 1/3 second): 5496	 num of players: 8
network id:32	 length(x 1/3 second): 5778	 num of players: 8
network id:33	 length(x 1/3 second): 7431	 num of players: 8
network id:34	 length(x 1/3 second): 10611	 num of players: 8
network id:35	 length(x 1/3 second): 7011	 num of players: 7
network id:36	 length(x 1/3 second): 7212	 num of players: 7
network id:37	 length(x 1/3 second): 4698	 num of players: 8
network id:38	 length(x 1/3 second): 4926	 num of players: 7
network id:39	 length(x 1/3 second): 3678	 num of players: 7
network id:40	 length(x 1/3 second): 6939	 num of players: 8
network id:41	 length(x 1/3 second): 7323	 num of players: 8
network id:42	 length(x 1/3 second): 8661	 num of players: 8
network id:43	 length(x 1/3 second): 6048	 num of players: 7
network id:44	 length(x 1/3 second): 8307	 num of players: 6
network id:45	 length(x 1/3 second): 7023	 num of players: 6
network id:46	 length(x 1/3 second): 9183	 num of players: 7
network id:47	 length(x 1/3 second): 7428	 num of players: 7
network id:48	 length(x 1/3 second): 2904	 num of players: 7
network id:49	 length(x 1/3 second): 5742	 num of players: 7
network id:50	 length(x 1/3 second): 4758	 num of players: 6
network id:51	 length(x 1/3 second): 7320	 num of players: 7
network id:52	 length(x 1/3 second): 5553	 num of players: 6
network id:53	 length(x 1/3 second): 5961	 num of players: 8
network id:54	 length(x 1/3 second): 7326	 num of players: 8
network id:55	 length(x 1/3 second): 6828	 num of players: 7
network id:56	 length(x 1/3 second): 8286	 num of players: 8
network id:57	 length(x 1/3 second): 6420	 num of players: 8
network id:58	 length(x 1/3 second): 10710	 num of players: 8
network id:59	 length(x 1/3 second): 4518	 num of players: 7
network id:60	 length(x 1/3 second): 6729	 num of players: 7
network id:61	 length(x 1/3 second): 8499	 num of players: 8

Ignore cells below

In [104]:
def preprocess(data_name):
    """
    u: Users
    i: Items
    ts: Timestamps
    label: Dynamic node labels
    feat: Interaction features
    
    See JODIE paper for deatials about the meaning of user and item
    """
    u_list, i_list, ts_list, label_list, deceiver_label_list = [], [], [], [], []
    feat_l = []
    idx_list = []
    
    with open(data_name) as f:
        
        s = next(f)
        
        for idx, line in enumerate(f):
            e = line.strip().split(',')
            u = int(e[0])
            i = int(e[1])
            ts = float(e[2])
            label = float(e[3])
            feat = float(e[4])
            deceiver_label = float(e[5]) #np.array([float(x) for x in e[5:]])
        
            u_list.append(u)
            i_list.append(i)
            ts_list.append(ts)
            label_list.append(label)
            idx_list.append(idx)
            feat_l.append(feat)
            deceiver_label_list.append(deceiver_label)
        
    return pd.DataFrame({'u': u_list,
                         'i': i_list,
                         'ts': ts_list,
                         'label': label_list,
                         'idx': idx_list,
                         'deceiver_label': deceiver_label_list
                        }), np.array(feat_l)

In [1]:
import numpy as np
import pandas as pd

graph_df = pd.read_csv('./TGN-master/data/ml_network_0.csv')

In [142]:
graph_df['deceiver_label'] = graph_df['deceiver_label'].apply(lambda x: [int(val) for val in x[1:-1].split('.') if val.strip().isnumeric()])
graph_df.head()

   Unnamed: 0  u   i   ts  label  idx         deceiver_label
0           0  2  15  2.0    0.0    1  [0, 0, 1, 0, 1, 0, 1]
1           1  3  15  3.0    0.0    2  [0, 0, 1, 0, 1, 0, 1]
2           2  4  14  4.0    0.0    3  [0, 0, 1, 0, 1, 0, 1]
3           3  5  11  5.0    0.0    4  [0, 0, 1, 0, 1, 0, 1]
4           4  6   8  6.0    0.0    5  [0, 0, 1, 0, 1, 0, 1]

In [6]:
graph_df['u'].unique(), graph_df['i'].unique()

(array([2, 3, 4, 5, 6, 7, 1], dtype=int64),
 array([15, 14, 11,  8, 10, 13, 12,  9], dtype=int64))